#!/usr/bin/env python3
"""
Async_comprehension
"""
from typing import List

async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """
    returns random numbers generated by async_generator async
    """
    return [val async for val in async_generator()]
